apiVersion: v2
# StackStorm version which refers to Docker images tag
appVersion: "3.8"
name: stackstorm-ha
version: 0.110.0
description: StackStorm K8s Helm Chart, optimized for running StackStorm in HA environment.
home: https://stackstorm.com/
icon: https://landscape.cncf.io/logos/stack-storm.svg
source:
  - https://github.com/stackstorm/stackstorm-k8s
keywords:
  - st2
  - stackstorm
  - devops
  - SRE
  - automation
  - chatops
  - event-driven
  - auto-remediation
  - IFTTT
  - HA
maintainers:
  - name: Eugen Cusmaunsa
    email: armab@stackstorm.com
    url: https://github.com/armab
details:
  This Helm chart is a fully installable app that codifies StackStorm cluster deployment optimized for HA and K8s environment.
  RabbitMQ-HA, MongoDB-HA clusters and Redis coordination backend st2 relies on will be deployed as 3rd party chart dependencies.
  For configuration details please check default values.yaml and README.
dependencies:
  - name: rabbitmq
    version: 7.2.2
    repository: oci://registry-1.docker.io/bitnamicharts/redis
    condition: rabbitmq.enabled
  - name: mongodb
    version: 7.0.2
    repository: oci://registry-1.docker.io/bitnamicharts/mongodb
    condition: mongodb.enabled
  - name: external-dns
    version: 0.13.6
    repository: oci://registry-1.docker.io/bitnamicharts/external-dns
    condition: external-dns.enabled
  - name: redis
    version: 7.2.2
    repository: oci://registry-1.docker.io/bitnamicharts/redis
    condition: redis.enabled
