dependencies:
  - name: rabbitmq-ha
    version: 1.8.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: mongodb-replicaset
    version: 3.5.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    alias: mongodb-ha
  - name: docker-registry
    version: 1.5.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: docker-registry.enabled
  - name: kube-registry-proxy
    version: 0.2.2
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: docker-registry.enabled
