{{- if not ( .Values.st2.tls.certificate_issuer.existing ) -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.st2.tls.certificate_issuer.name }}
  namespace: "{{ $.Release.Namespace }}"
spec:
  ca:
    secretName: {{ .Values.st2.tls.certificate_issuer.name }}-tls
---
apiVersion: v1
{{- include "stackstorm-ha.internal_tls.ca" .  }}
kind: Secret
metadata:
  name: {{ .Values.st2.tls.certificate_issuer.name }}-tls
  namespace: "{{ $.Release.Namespace }}"
type: kubernetes.io/tls
{{- end -}}
