---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-auth
  annotations:
    description: StackStorm username and password, used for basic .htaccess auth
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # Username, used to login to StackStorm system (default: st2admin)
  username: {{ required "A valid secret 'st2.username' is required for StackStorm auth!" .Values.secrets.st2.username | b64enc | quote }}
  # Password, used to login to StackStorm system (default: Ch@ngeMe)
  password: {{ required "A valid secret 'st2.password' is required for StackStorm auth!" .Values.secrets.st2.password | b64enc | quote }}
