# Notify users about breaking change regarding secrets, to not destroy current installations
{{- $deprecated_username := (default (dict) (default (dict) .Values.secrets).st2).username }}
{{- $deprecated_password := (default (dict) (default (dict) .Values.secrets).st2).pasword }}
{{- if or $deprecated_username $deprecated_password }}
{{- fail "Please update your values! Values for username and password moved from secrets.st2.* to st2.*" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $name := print .Release.Name "-st2-auth" }}
  name: {{ $name }}
  annotations:
    description: StackStorm username and password, used for basic .htaccess auth
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # Username, used to login to StackStorm system (default: st2admin)
  username: {{ required "A valid secret 'st2.username' is required for StackStorm auth!" .Values.st2.username | b64enc | quote }}
  # Password, used to login to StackStorm system (default: auto-generated)
{{- $previous := lookup "v1" "Secret" .Release.Namespace $name }}
{{- if and $previous (not .Values.st2.password) }}
  password: {{ $previous.data.password }}
{{ else }}
  password: {{ default (randAlphaNum 12) .Values.st2.password | b64enc | quote }}
{{ end }}
{{- if .Values.jobs.api_key }}
  # api_key used by helm Jobs to login to StackStorm (instead of username/password)
  jobs_api_key: {{ .Values.jobs.api_key | b64enc | quote }}
{{- end }}
