# Notify users about breaking change regarding secrets, to not destroy current installations
{{- $deprecated_username := (default (dict) (default (dict) .Values.secrets).st2).username }}
{{- $deprecated_password := (default (dict) (default (dict) .Values.secrets).st2).pasword }}
{{- if or $deprecated_username $deprecated_password }}
{{- fail "Please update your values! Values for username and password moved from secrets.st2.* to st2.*" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- $name := print .Release.Name "-st2-auth" }}
  name: {{ $name }}
  annotations:
    description: StackStorm username and password, used for basic .htaccess auth
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # Username, used to login to StackStorm system (default: st2admin)
  ST2_AUTH_USERNAME: {{ required "A valid secret 'st2.username' is required for StackStorm auth!" .Values.st2.username | b64enc | quote }}
  # Password, used to login to StackStorm system (default: auto-generated)
{{- $previous := lookup "v1" "Secret" .Release.Namespace $name }}
{{- if and $previous (not .Values.st2.password) }}
  ST2_AUTH_PASSWORD: {{ default $previous.data.password $previous.data.ST2_AUTH_PASSWORD }}
{{ else }}
  ST2_AUTH_PASSWORD: {{ default (randAlphaNum 12) .Values.st2.password | b64enc | quote }}
{{ end }}
