{{- if .Values.st2.customPyPiRepUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-custom-pip-conf
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  pip.conf: {{ tpl (.Files.Get "conf/pip.conf") . | b64enc }}
{{- end }}
