{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stackstorm-ha.serviceAccountName" . }}
  {{- if .Values.serviceAccount.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.serviceAccountAnnotations | nindent 4 }}
  {{- end }}
  labels: {{- include "stackstorm-ha.labels" (template "stackstorm-ha.name" .) | nindent 4 }}
  {{- if .Values.serviceAccount.pullSecret }}
imagePullSecrets:
- name: "{{ .Values.serviceAccount.pullSecret }}"
  {{- end }}
{{- end }}
